name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm
      - run: pnpm install
      - run: pnpm run build
      - run: ls
      - run: pwd
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: lnbiuc/blog-next-view:latest
      - name: ssh pipelines
        uses: cross-the-world/ssh-pipeline@master
        env:
          WELCOME: ssh pipeline
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          user: ${{ secrets.SERVER_USERNAME }}
          pass: ${{ secrets.SERVER_PASSWORD }}
          connect_timeout: 10s
          script: |
            docker pull lnbiuc/blog-next-view:latest
            docker stop blog-next-view
            docker rm blog-next-view
            docker run -d -p 3000:3000 --name blog-next-view --restart always -m 512m --network docker-net lnbiuc/blog-next-view:latest
      - name: Tencent CDN
        uses: keithnull/tencent-cloud-cdn-purge-cache@v1.0
        env:
          SECRET_ID: ${{ secrets.SECRET_ID}}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          PATHS: https://vio.vin/
          FLUSH_TYPE: flush